# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Currency title')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Currency values title')),
                ('values', models.FloatField(verbose_name='Value')),
            ],
        ),
        migrations.AddField(
            model_name='currency',
            name='values',
            field=models.ManyToManyField(blank=True, to='main.CurrencyValues'),
        ),
    ]
