# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyvalues',
            old_name='values',
            new_name='value',
        ),
    ]
