# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161003_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Currency title'),
        ),
    ]
